---
name: Build and publish
on:
  push:
    branches:
      - '**'
  pull_request:
    types:
      - opened
      - edited
  workflow_dispatch:

jobs:
  build-java-source:
    name: Build jar and test
    uses: OHSU-OCTRI/shared-workflows/.github/workflows/java-build.yaml@main
    with:
      java_version: '17'
      publish_to_github_packages: ${{ github.ref == 'refs/heads/main' || github.ref_type == 'tag' }}publish_to_maven_central      publish_to_maven_central: ${{ github.ref == 'refs/heads/main' || github.ref_type == 'tag' }}
      publish_to_maven_central: ${{ github.ref == 'refs/heads/main' || github.ref_type == 'tag' }}
    secrets: inherit