---
name: Build and test
on:
  push:
    branches-ignore:
      - 'main'
      - 'dependabot/**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  build-java-source:
    name: Build jar and test
    uses: OHSU-OCTRI/shared-workflows/.github/workflows/java-test-build.yaml@main
    with:
      java_version: '17'
    # Does not inherit secrets due to security changes in automated workflows